name: Integration Tests

on:
  push:
    branches: # Run on push to main branch
      - master
  schedule: # Run everyday at 12am EST
    - cron: '0 5 * * *'
  workflow_dispatch: # Allow run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java (OpenJDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # You can also use 'adopt', 'zulu', etc.
          java-version: '17'
          cache: maven

      # Install custom dependencies
      - name: Install Custom Dependencies
        run: |
          mvn install:install-file -Dfile=libs/dcm4che-core-5.33.1.jar \
            -DgroupId=org.dcm4che \
            -DartifactId=dcm4che-core \
            -Dversion=5.33.1 \
            -Dpackaging=jar
          
          mvn install:install-file -Dfile=libs/dcm4che-net-5.33.1.jar \
            -DgroupId=org.dcm4che \
            -DartifactId=dcm4che-net \
            -Dversion=5.33.1 \
            -Dpackaging=jar
          
          mvn install:install-file -Dfile=libs/dcm4che-json-5.33.1.jar \
            -DgroupId=org.dcm4che \
            -DartifactId=dcm4che-json \
            -Dversion=5.33.1 \
            -Dpackaging=jar

      # Build with Maven & run integration tests
      - name: Build with Maven
        run: mvn clean package -X